### ISSUE TITLE
Update version functions, shortcodes, page and single-photo_essay files

### ISSUE THREAD

**Issue by cadie** [UCF/Pegasus-Theme#62]
Update /v6/ functions.php, shortcodes.php, page.php, single-photo_essay.php and any other related or referenced functionality/markup/styles.

**Comment by rjbruneel** [comment]
### Pegasus Shortcodes

@cadie & @cjg89 A list of the shortcodes listed in the version shortcode.php with possible replacements and descriptions of the shortcode.

**search_form** - _?_
Display search form

**well** - _?_
Displays a Bootstrap well.

**site-url** - _?_
Returns the site URL.

**post-type-search** - _?_
Post search

**archive-search** - _?_
A modified version of Generic post type search. Generates searchable lists of stories, grouped by their respective issue.

**slideshow** - _?_
Photo Essay Slideshow

**photo_essay** - _?_
Photo Essay

**lead**- _?_
Wrap arbitrary text in .lead paragraph

**callout** - _?_
Create a full-width callout box.

**header_callout** - _?_

**google-remarketing** - _?_
Inserts a Google Remarketing tag.

**caption** - _Is this available via Athena?_
Wrap arbitrary text in .caption paragraph. Destroy WordPress' existing caption shortcode.

**sidebar** - _Athena row and col_
Create a floating sidebar.

**chart** - _ChartJS Plugin_
ChartJS, add a chart.

**clearfix** -  _Unnecessary_
Inserts an empty clearfix div.

**button** - _Athena button_
Inserts a Bootstrap button.

**blockquote** - _WYSIWYG_
Wrap arbitrary text in blockquote

**divider** - _WYSIWYG_
Return a hr element

**social_buttons** - _UCF Social Plugin_
Display social buttons for the current page/post.

**background_image** - _Athena media background shortcode_
Same as [image], but returns markup safe to use within an element as a background image


_Media and images can be inserted using the WP media button for the shortcodes below_

**sc_image**
Search for an image by file name and return its URL.

**static-image**
Link to a static image. Requires extension

**media**
Search for some arbitrary media in the media library.

**photo**
Uses sc_image to get an image URL and display it in an <img> tag with optional styling parameters.

**Comment by cjg89** [comment]
#82 removes the following:
- **search_form** not used
- **well** wells are no longer a thing/use Athena cards or jumbotrons instead
- **post-type-search** not used
- **slideshow** really shouldn't be using this moving forward/use photo essay template instead
- **lead** available with Athena WYSIWYG formatting tools
- **callout** not really going to be feasible with the new two-col layout we're adding in #81
- **header_callout** currently used on the Give page, but should be replaceable now that we have a full-width page template available
- **caption** Athena SC plugin takes care of this
- **sidebar** not really going to be feasible with the new two-col layout we're adding in #81
- **chart** - might be the only one I'm not totally sure about removing.  Open to opinions on this--we could look into adding support for the UCF Chart plugin, but might be easier to just leave as-is if we can't easily load conditionally per-version
- **clearfix** - likely won't be needed anymore since we're no longer using a float-based grid or floating sidebars
- **button** conflicts with Athena buttons
- **blockquote** available with Athena WYSIWYG formatting tools
- **divider** available in the WYSIWYG

Additionally, the image-related shortcodes below have all been removed in favor of using the Athena SC's provided `<img>` tag formatting, and media backgrounds:
- **background_image** 
- **image**
- **static-image** 
- **media**
- **photo**

**Comment by rjucf** [comment]
Updated About page in DEV and QA.
https://wwwdev.cm.ucf.edu/pegasus/about/
https://wwwqa.ucf.edu/pegasus/about/
